import type { PrintableDocumentPayload, PrintableTableColumn } from "../../types/print";
import type { PrintAppearance, PrintFormat, PrintOrientation } from "../../services/print/types";
import { resolvePageSizeMm } from "../../services/print/types";
import { buildAppearanceStyles, printStyles } from "./styles";
import { renderDayBookContent } from "./dayBook";

export function escapeHtml(value: unknown) {
  const text = String(value ?? "");
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export type PrintPageOptions = {
  format: PrintFormat;
  orientation: PrintOrientation;
  widthMm?: number;
  heightMm?: number;
  marginTopMm: number;
  marginRightMm: number;
  marginBottomMm: number;
  marginLeftMm: number;
  appearance: PrintAppearance;
};

export function isPartyLabel(label: string) {
  const normalized = label.trim().toLowerCase();
  return ["party", "customer", "supplier", "account"].includes(normalized);
}

export function alignClass(col: PrintableTableColumn) {
  if (col.align === "right") return "align-right";
  if (col.align === "center") return "align-center";
  return "";
}

export function renderMeta(payload: PrintableDocumentPayload) {
  const meta = payload.meta;
  if (!meta) return "";
  const chips: Array<{ text: string; className?: string }> = [];
  if (meta.dateFrom || meta.dateTo) {
    chips.push({
      text: `Period: ${escapeHtml(meta.dateFrom || "-")} - ${escapeHtml(meta.dateTo || "-")}`,
    });
  }
  if (meta.createdBy) chips.push({ text: `Prepared By: ${escapeHtml(meta.createdBy)}` });
  if (meta.createdAt) chips.push({ text: `Prepared At: ${escapeHtml(meta.createdAt)}` });
  if (meta.filters) {
    for (const [key, val] of Object.entries(meta.filters)) {
      const isParty = isPartyLabel(key);
      chips.push({
        text: `${escapeHtml(key)}: ${escapeHtml(val)}`,
        className: isParty ? "party-chip" : undefined,
      });
    }
  }
  if (chips.length === 0) return "";
  return `
    <div class="meta">
      ${chips
        .map(
          (chip) =>
            `<div class="meta-chip${chip.className ? ` ${chip.className}` : ""}">${chip.text}</div>`,
        )
        .join("")}
    </div>
  `;
}

export function renderBrand(payload: PrintableDocumentPayload, appearance: PrintAppearance) {
  const logo =
    appearance.showLogo && payload.company.logoUrl
      ? `<img class="brand-logo" src="${escapeHtml(payload.company.logoUrl)}" alt="logo" />`
      : "";
  return `
    <div class="brand">
      ${logo}
      <div>
        <div class="brand-title">${escapeHtml(payload.company.name)}</div>
        <div class="brand-meta">
          ${payload.company.address ? `${escapeHtml(payload.company.address)}<br/>` : ""}
          ${payload.company.phone ? `Phone: ${escapeHtml(payload.company.phone)}` : ""}
          ${payload.company.ntn ? ` | NTN: ${escapeHtml(payload.company.ntn)}` : ""}
          ${payload.company.strn ? ` | STRN: ${escapeHtml(payload.company.strn)}` : ""}
        </div>
      </div>
    </div>
  `;
}

export function docKeyClass(docKey: unknown) {
  return `doc-key-${String(docKey).replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`;
}

/**
 * The single page shell shared by every printable document. Paper size, margins
 * and appearance are applied here and nowhere else, so a layout fix lands on all
 * modules at once.
 */
export function renderPageShell(options: {
  payload: PrintableDocumentPayload;
  page: PrintPageOptions;
  bodyClass?: string;
  content: string;
}) {
  const { payload, page, content } = options;
  const size = resolvePageSizeMm(page);
  const appearance = page.appearance;
  const watermark = payload.settings?.showWatermark
    ? `<div class="watermark"><span class="watermark-text">${escapeHtml(
        payload.settings?.watermarkText || payload.company.name,
      )}</span></div>`
    : "";
  const bodyClasses = [
    docKeyClass(payload.docKey),
    `paper-${String(page.format).toLowerCase()}`,
    `color-${appearance.colorMode}`,
    options.bodyClass || "",
  ]
    .filter(Boolean)
    .join(" ");

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${escapeHtml(payload.title)}</title>
    <style>
      ${printStyles}
      :root {
        --page-width: ${size.width}mm;
        --page-height: ${size.height}mm;
        --page-margin-top: ${page.marginTopMm}mm;
        --page-margin-right: ${page.marginRightMm}mm;
        --page-margin-bottom: ${page.marginBottomMm}mm;
        --page-margin-left: ${page.marginLeftMm}mm;
      }
      ${buildAppearanceStyles(appearance)}
    </style>
  </head>
  <body class="${bodyClasses}">
    <div class="page">
      ${watermark}
      <div class="doc">
        ${content}
      </div>
      <div class="footer">
        <div>Generated by Rice Mill ERP</div>
        <div>${escapeHtml(payload.title)}</div>
      </div>
    </div>
  </body>
</html>
`;
}

function renderSections(payload: PrintableDocumentPayload) {
  if (!payload.sections || payload.sections.length === 0) return "";
  const isInvoice = String(payload.docKey || "").startsWith("invoice.");
  if (isInvoice) {
    return `
      <div class="summary-table">
        <div class="summary-title">Summary</div>
        <table>
          <tbody>
            ${payload.sections
              .map(
                (s) => `
              <tr class="${s.highlight ? "highlight" : ""}">
                <td class="label">${escapeHtml(s.label)}</td>
                <td class="value align-right">${escapeHtml(s.value)}</td>
              </tr>
            `,
              )
              .join("")}
          </tbody>
        </table>
      </div>
    `;
  }
  return `
      <div class="sections">
        ${payload.sections
          .map(
            (s) => `
          <div class="section-card${s.highlight ? " highlight" : ""}${isPartyLabel(s.label) ? " party" : ""}">
            <div class="label">${escapeHtml(s.label)}</div>
            <div class="value">${escapeHtml(s.value)}</div>
          </div>
        `,
          )
          .join("")}
      </div>
    `;
}

export function renderTable(payload: PrintableDocumentPayload) {
  const table = payload.table;
  if (!table) return "";

  const header = `
    <thead>
      <tr>
        ${table.columns
          .map((c) => `<th class="${alignClass(c)}" style="${c.width ? `width:${c.width};` : ""}">${escapeHtml(c.label)}</th>`)
          .join("")}
      </tr>
    </thead>
  `;

  const rows = table.rows
    .map((row) => {
      const group = row.__group as string | undefined;
      const isGroupTotal = Boolean(row.__groupTotal);
      if (group) {
        return `<tr class="group-row"><td colspan="${table.columns.length}">${escapeHtml(group)}</td></tr>`;
      }
      return `
        <tr class="${isGroupTotal ? "totals-row" : ""}">
          ${table.columns
            .map((c) => {
              const val = row[c.key];
              const escaped = escapeHtml(val ?? "");
              const htmlVal = escaped.replace(/\n/g, "<br/>");
              return `<td class="${alignClass(c)}">${htmlVal}</td>`;
            })
            .join("")}
        </tr>
      `;
    })
    .join("");

  const totals = table.totalsRow
    ? `
      <tr class="totals-row">
        ${table.columns
          .map((c) => `<td class="${alignClass(c)}">${escapeHtml(table.totalsRow?.[c.key] ?? "")}</td>`)
          .join("")}
      </tr>
    `
    : "";

  return `
    <table>
      ${header}
      <tbody>
        ${rows}
        ${totals}
      </tbody>
    </table>
  `;
}

function renderNotes(payload: PrintableDocumentPayload) {
  if (!payload.notes) return "";
  return `<div class="notes"><strong>Notes:</strong> ${escapeHtml(payload.notes)}</div>`;
}

function renderSignatures(payload: PrintableDocumentPayload) {
  if (payload.docKey !== "voucher.journal") return "";
  const signatures = payload.signatures || [
    { label: "Prepared By" },
    { label: "Approved By" },
    { label: "Received By" },
  ];
  return `
    <div class="signatures">
      ${signatures.map((s) => `<div class="signature">${escapeHtml(s.label)}</div>`).join("")}
    </div>
  `;
}

export function renderDocumentHtml(payload: PrintableDocumentPayload, options: PrintPageOptions) {
  if (payload.docKey === "report.dayBook") {
    const dayBook = renderDayBookContent(payload, options.appearance, {
      escapeHtml,
      renderBrand,
      renderMeta,
      renderTable,
    });
    return renderPageShell({ payload, page: options, content: dayBook });
  }

  const content = `
    <div class="header">
      ${renderBrand(payload, options.appearance)}
      <div class="doc-title">
        <h1>${escapeHtml(payload.title)}</h1>
        ${payload.docNo ? `<div class="doc-no">Document No: ${escapeHtml(payload.docNo)}</div>` : ""}
      </div>
    </div>
    ${renderMeta(payload)}
    ${renderSections(payload)}
    ${renderTable(payload)}
    ${renderNotes(payload)}
    ${renderSignatures(payload)}
  `;

  return renderPageShell({ payload, page: options, content });
}
